### ISSUE TITLE
Increase the range that is considered "On Target"

### ISSUE THREAD

**Issue by lightmaster** [LazeMSS/OctoPrint-TopTemp#10]
When the Temps get right on target, they will show the flag saying they are on target. However, it seems that "on target" means to be within a few hundredths of a degree of the target temp, so they almost never show as on target. Can this be changed such that +- 0.5 degrees is considered on target?

**Comment by LazeMSS** [comment]
Yes good idea

**Comment by LazeMSS** [comment]
Should be fixed in https://github.com/LazeMSS/OctoPrint-TopTemp/releases/tag/0.0.0.2

Please reopen if not fixed/working.
