### ISSUE TITLE
Small cosmetic Issue

### ISSUE THREAD

**Issue by mike-bee** [LazeMSS/OctoPrint-TopTemp#105]
I am running all latest stable versions and have a small issue with the TopTemp appearance: I am experiencing an unreasonable big gap between the icon (top most) and the readout (bottom most). At least it is bigger than on the image in your ReadMe on the Code tab.

![TopTemp](https://github.com/LazeMSS/OctoPrint-TopTemp/assets/30027622/47830733-7adb-4331-91fe-9cfde80d35f7)

**Comment by LazeMSS** [comment]
Will look when back from vacation

**Comment by LazeMSS** [comment]
Maybe its a theme - do you have the same problem with all themes?

**Comment by mike-bee** [comment]
Welcome back - hope you had a good time.
I guess you refer to "UI Customizer" themes. Yes it's the same in all. Plaese see Default theme:
![Default](https://github.com/LazeMSS/OctoPrint-TopTemp/assets/30027622/ea2368ce-d697-4c4c-9371-e0bda06c7ae3)

**Comment by LazeMSS** [comment]
I can't recreate it - might there might another plugin running etc. please post screenshot of entire top bar

**Comment by mike-bee** [comment]
![Entire Top Bar](https://github.com/LazeMSS/OctoPrint-TopTemp/assets/30027622/cc4de271-a017-4eb2-9d8c-47b1ad0d8b07)
![PI1](https://github.com/LazeMSS/OctoPrint-TopTemp/assets/30027622/8b769f09-060d-469a-a242-18082a0caf8f)
![PI2](https://github.com/LazeMSS/OctoPrint-TopTemp/assets/30027622/e2c4d9ff-6938-413d-b5d2-67688526150f)

**Comment by LazeMSS** [comment]
Please check you don't have your browser zoomed in in font size

**Comment by mike-bee** [comment]
Chrome zoom level is at 100%. I tested zooming in and out. The issue disappeared from 175% upwards:
![175](https://github.com/LazeMSS/OctoPrint-TopTemp/assets/30027622/cc45f620-d322-4cc4-8801-9de7c9653ce6)

**Comment by LazeMSS** [comment]
Maybe an overflow issue with the printer label etc. - seems strange nobody else has this issue :/

**Comment by mike-bee** [comment]
Too bad. I can try changing my settings and watch for improvement. Anything you recommend to start with or focus on?

**Comment by mike-bee** [comment]
**Good news**: I was able to recover the look-and-feel. I started gradually removing labels first, then complete items. No change.
Then uninstalled (including data) and reinstalled Top Temp and since the original look-and-feel is back. GREAT. I reconfigured only the bare minimum. Still looking good.
**Bad news**: No chance of analyzing the issue any further.
