### ISSUE TITLE
Add Hotend and Part Cooling Fan Speed

### ISSUE THREAD

**Issue by lightmaster** [LazeMSS/OctoPrint-TopTemp#13]
I don't know how to do it, but it would be nice to be able to show the speeds of various fans using this. At the vary least, the Part Cooling Fan, but also the Hotend Fan if its set to be automatic instead of always on.

**Comment by LazeMSS** [comment]
Normally these cant be read but I will look into getting them from the gcode sent

**Comment by lightmaster** [comment]
Not sure how they do it, but DisplayLayerProgress is able to get the cooling part fan, just type in `[fanspeed]` where you want it:
```
Fan: <span style='display: inline-block;width:42px;'>[fanspeed]</span>
```

**Comment by LazeMSS** [comment]
Yes I was guessing they were using the gcode - this will not work if you change the fan speed directly on the printer. But its better than nothing. I will look into it and add it together with the other stuff new stuff I will be adding.

**Comment by LazeMSS** [comment]
@lightmaster  which gcode can enable/disable the hotend fan? I know of M106 for fanspeed but not hotend fand

**Comment by lightmaster** [comment]
Hot end is either always on with 12/24v constant, or hooked up to a mosfet and automatically on when hotend temp is above a certain to set in `Configuration_adv.h`. If only for safety reasons, I doubt you can directly control the hotend fan with gcode.

**Comment by LazeMSS** [comment]
This is fixed in the next release - please test/try by following the below guide:
```
Open Settings, then click Plugin Manager
At the bottom click "Get more.."
In the input field below "... from URL" paste in: https://github.com/LazeMSS/OctoPrint-TopTemp/archive/develop.zip
Click Install
```

**Comment by lightmaster** [comment]
Once I noticed the default settings for `Only while printer is printing` and disabled that, looks like it's working great.

**Comment by LazeMSS** [comment]
Reopen will close when public release is out 😄

**Comment by LazeMSS** [comment]
Closing - fixed in: https://github.com/LazeMSS/OctoPrint-TopTemp/releases/tag/0.0.1.0

Please reopen if not fixed
