### ISSUE TITLE
CPU temperature not sortable

### ISSUE THREAD

**Issue by unclej84** [LazeMSS/OctoPrint-TopTemp#14]
When trying to re-arrange position of CPU temperature in sort list it disappears on save and stays in last position (see Screenshots).

Before saving:
![TopTemp_before_save](https://user-images.githubusercontent.com/60842330/105804435-1b28d900-5fa0-11eb-807f-44cf6a2d29f4.jpg)

During saving:
![TopTemp_on_save](https://user-images.githubusercontent.com/60842330/105804451-2419aa80-5fa0-11eb-904d-1cf47b23de60.jpg)

**Comment by LazeMSS** [comment]
Bug found and fixed in next release

**Comment by LazeMSS** [comment]
Should be fixed in: https://github.com/LazeMSS/OctoPrint-TopTemp/releases/tag/0.0.0.3

I'm closing for now - if not fixed please reopen this :)
