### ISSUE TITLE
Feature Request: Allow Themeing

### ISSUE THREAD

**Issue by MasterDomino** [LazeMSS/OctoPrint-TopTemp#27]
Hello,

I would like to request a feature added, as i tried to manually add changes to themeify but that wont work as the script executes after themeify enforces its rules .popover-title and .popover-content cannot be edited.

while writing this i have in mind that the css follow other theme settings set by themeify by reading what theme is enabled.

Im thankful for consideration.

**Comment by LazeMSS** [comment]
I will try - have you tried adding !important to your custom css? :)

**Comment by MasterDomino** [comment]
Have just tried that and it doesnt seem to work, i dont really know if it's themeifies fault or me being a dummy, also thanks for the great plugin really adds readability

**Comment by LazeMSS** [comment]
Im working on implemeting my own themes :)

**Comment by MasterDomino** [comment]
this works beautifully with UI Customizer plugin making Themeify kinda obsolete, i guess this can be closed(?)

**Comment by LazeMSS** [comment]
Closing
