### ISSUE TITLE
Feature request: Themify charts

### ISSUE THREAD

**Issue by Fank** [LazeMSS/OctoPrint-TopTemp#37]
It would be nice to use the default theme or custom define the colors for the charts.
In my example i am using the plugin [UI Customizer](https://github.com/LazeMSS/OctoPrint-UICustomizer/) and it looks like:
![image](https://user-images.githubusercontent.com/1900106/109829034-799b4400-7c3d-11eb-8805-46bdf65707fe.png)

Would be nice if it could use the same colors as in the temperature tab, if default theme is choosen:
![image](https://user-images.githubusercontent.com/1900106/109829463-d860bd80-7c3d-11eb-8c60-1c46bba49881.png)

**Comment by LazeMSS** [comment]
Well this requires the theme authors to implement this feature - i will look into it.
I also make the UI Customizer plugin 😄

**Comment by Fank** [comment]
I know :P

**Comment by LazeMSS** [comment]
Now released

**Comment by Fank** [comment]
You should update the pic in the Readme too :D

**Comment by LazeMSS** [comment]
Done...
