### ISSUE TITLE
Feature request: disable custom

### ISSUE THREAD

**Issue by Fank** [LazeMSS/OctoPrint-TopTemp#38]
By default there is a "Cooling fan speed" which i don't have setup yet, so its not available.
But it i sometimes stuck in a "loading" animation, which i don't want see.

So i would like to disable one, until i added it correctly.

**Comment by LazeMSS** [comment]
You can just delete it

**Comment by Fank** [comment]
I know, but i wanted to let it stay for future use without recreating it.

**Comment by LazeMSS** [comment]
Its already in there as a predefined option - so just delete it and then add again - its just select: "Gcode sent" and then select.

Im trying to slim down the number of options in the UI :)
