### ISSUE TITLE
Problems in displaying bed and extruders temps

### ISSUE THREAD

**Issue by EddyMI3d** [LazeMSS/OctoPrint-TopTemp#4]
Hello!
Nice work. But did I miss something? <del>I get the SoC/CPU temp displayed, but the rest is turning wheels...</del>

Yes: I was not connected to the printer... Sorry

![grafik](https://user-images.githubusercontent.com/8533327/105629728-084dc180-5e45-11eb-813a-397aafe49e21.png)

**Comment by LazeMSS** [comment]
Yes I will fix that bug in the next. No need to show spinners when not operational.

**Comment by LazeMSS** [comment]
Should be fixed in https://github.com/LazeMSS/OctoPrint-TopTemp/releases/tag/0.0.0.2

Please reopen if not fixed/working.
