### ISSUE TITLE
[FR] Add ability to update Part Cooling Fan regardless of how its speed was set

### ISSUE THREAD

**Issue by lightmaster** [LazeMSS/OctoPrint-TopTemp#44]
If you enable <s>`#define HOST_ACTION_COMMANDS` and `#define HOST_PROMPT_SUPPORT`</s> `#define REPORT_FAN_CHANGE` within `Configuration_adv.h`, then Marlin will echo back over terminal <s>a lot of commands, including</s> the fan speed. This includes setting fan speed from the basic LCD with an encoder wheel and also TFTs touch screen. <s>This should be able to greatly expand the available options of TopTemp and increase reliability of it being able to recognize when something changes.</s>

**Comment by LazeMSS** [comment]
Yes and if you do this then my plugin can filter for these results. I don't have a printer with marlin firmware so I can't test it. But if you have an example of what is returned when having this enable then maybe I can help but it's not something that needs to coded

**Comment by lightmaster** [comment]
`M106 P0 S127` is what it sends to terminal

**Comment by lightmaster** [comment]
I switched it from GCode Sent to From Printer and it works. Did not notice that option before.

**Comment by lightmaster** [comment]
What about combining GCode Sent and From Printer such that if you do not have `HOST_ACTION_COMMANDS` enabled, it will look at the gcode that you sent, and if you do have it enabled, it can see both the gcode you send and the gcode the printer reports back.

**Comment by LazeMSS** [comment]
Well I think people should setup what fits their printers.

**Comment by LazeMSS** [comment]
... and not quite sure how you wanted that to work

**Comment by lightmaster** [comment]
I was just thinking that they become a single combined entry. If it sees both a sent gcode and received from printer gcode, then they'd be the same since it's echoing back. Otherwise if it sees just a sent gcode, then it shows just the sent gcode.

**Comment by LazeMSS** [comment]
Yes both that would require even more monitoring.
Could you provide an example of how this should work. I don't want to implement something where my plugin sends gcode/commands to the printer

**Comment by lightmaster** [comment]
> If you enable `#define HOST_ACTION_COMMANDS` and `#define HOST_PROMPT_SUPPORT`

I was way off on the setting that I was talking about, its actually `#define REPORT_FAN_CHANGE`. And this only allows you to see the fan speed changes from any source, so probably not worth the effort to needlessly combine the Gcode Sent and From Printer bits into one.

**Comment by LazeMSS** [comment]
So close?
