### ISSUE TITLE
Shown timeline should be always the same

### ISSUE THREAD

**Issue by Fank** [LazeMSS/OctoPrint-TopTemp#45]
Bed, Tool 0 and CPU temperature shows alway a max of 10 minutes:   
![image](https://user-images.githubusercontent.com/1900106/110485022-83182680-80eb-11eb-80bd-db3a18225c50.png)

But Cooling fan speed shows a completly different timeline:   
![image](https://user-images.githubusercontent.com/1900106/110485049-890e0780-80eb-11eb-866a-4a2da205feeb.png)

It looks like it only counts the time when this option is enabled:    
![image](https://user-images.githubusercontent.com/1900106/110485532-0e91b780-80ec-11eb-8de3-cfebc8200909.png)

**Comment by LazeMSS** [comment]
I have a fix on the way.

But the cooling fan speed is only updated when a gcode is sent to alter the speed thats why its sporadic.

**Comment by LazeMSS** [comment]
Fixed/closed in https://github.com/LazeMSS/OctoPrint-TopTemp/releases/tag/0.0.1.3

Please reopen if not fixed.
