### ISSUE TITLE
[Feature Request] Make widgets fixed width

### ISSUE THREAD

**Issue by ThorstenWirth** [LazeMSS/OctoPrint-TopTemp#46]
With CPU load and frequency the widgets and other items in the top bar jump all over the place.

https://user-images.githubusercontent.com/31453908/111276075-38406680-8637-11eb-88a4-caac5763f4c3.mp4

Adding an option to make the widgets a fixed width might stop this behavior and make the widgets look more uniform/coherent

**Comment by LazeMSS** [comment]
Yes its on the todo list.

**Comment by LazeMSS** [comment]
Fixed/closed in https://github.com/LazeMSS/OctoPrint-TopTemp/releases/tag/0.0.1.3

Please reopen if not fixed.
