### ISSUE TITLE
Help for Fan in %

### ISSUE THREAD

**Issue by luco85** [LazeMSS/OctoPrint-TopTemp#47]
Hello! i not understand how to have the fan value in %
So i add custom tab
- type: gcode send
- deactivate "input is a temperature value
- i use layer fan speed from menù
- ^M106.*?S([^ ]+) formula appears to sniff gcode

In post calculate i stop. i Try many value for calculation as "x" for x/255*100
How formula i need?
thanks

**Comment by LazeMSS** [comment]
Uppercase X?

**Comment by luco85** [comment]
Ya X sorry, i wrote wrong here
What formula i need to use?

**Comment by LazeMSS** [comment]
`X/255*100`

My settings:
![image](https://user-images.githubusercontent.com/69049371/112537566-22f1d780-8daf-11eb-810e-cf6e8fe222d0.png)

**Comment by luco85** [comment]
Ok thanks! I’ll try

**Comment by LazeMSS** [comment]
Okay closing. Reopen/comment if still not working

**Comment by luco85** [comment]
It work thanks! I thought that X was a generic parameter for example
