### ISSUE TITLE
CPU Temp Command & Enhancments

### ISSUE THREAD

**Issue by Pheelix** [LazeMSS/OctoPrint-TopTemp#5]
Not sure if the command path to my  vcgencmd isn't default.  But I had to change the pathing in settings to /usr/bin/vcgencmd measure_temp.   Had to modify some navbartemp files as well with same path, but will be using toptemp from here on out.

If my pathing to vcgencmd isn't the normal path then what you have defaulted, then go ahead and close this post.  But this is the pathing it gave me from a default install of octoprint on a RPI4.

**Comment by LazeMSS** [comment]
My plugin tests available know options and show the detected options as predefined. I think the RPI in the later distros have them in both paths. Basically if something is shown in the list under predefined means it worked when the plugin started.

Please post anything you have found that works for you/you have changed so I can test.

**Comment by Pheelix** [comment]
I just modifited the command to: 
/usr/bin/vcgencmd measure_temp|cut -d "=" -f2|cut -d"'" -f1
and it works perfectly.  Just had to replace /opt/vc/bin/ for the command above.

On another note.  I changed the Icons for bed and tool:
Bed: fas fa-solar-panel
Tool: fas fa-filter
I was trying to find a Line with heat was above it for bed and something close to what looks like a hotend but didn't manage to find anything :(.   So these seem pretty close.

Also a few suggestions.  Could you space out the Icon and the Text a little or maybe add a option to add X amount of space.
Text Size and Color options would be nice too.  Tho I have already added Custom CSS code for the size and color.  Couldn't figure out how to space the icons and text.  My CSS coding skills suck.

I know this is a new plugin and you are still working on it.  Just my input on it.  Liking it so far.

![image](https://user-images.githubusercontent.com/3882473/105638178-1fc98200-5e26-11eb-921f-ebdd2272d797.png)

**Comment by Pheelix** [comment]
Some quick photoshoping of what I was thinking.

![example 1](https://user-images.githubusercontent.com/3882473/105638607-5902f180-5e28-11eb-9b16-e5632ca0a3a0.png)
![example 2](https://user-images.githubusercontent.com/3882473/105638608-5902f180-5e28-11eb-8acc-762bbc81563a.png)

A option to put the Icons on the sides seems nice.  Again all up to you.

**Comment by LazeMSS** [comment]
There are two options tested regarding vcgencmd:
/usr/bin/vcgencmd measure_temp|cut -d "=" -f2|cut -d"'" -f1
/opt/vc/bin/vcgencmd measure_temp|cut -d "=" -f2|cut -d"'" -f1

So the one you posted should be on the list and added - both off them normally work - well its the same command normaly just with an alias/symlink.

I dont allow colors on the icons and text at the moment - this is done by using standard boostrap styling - this is to avoid conflicts with any themes etc. Although i might add it later.

I will look into having the icons to the different sides and more spacing.

**Comment by Pheelix** [comment]
Yep no problem on the colors, I can just use Custom CSS for that.

As for the vcgencmd.  This was the other predefined. cat /sys/class/thermal/thermal_zone0/temp | sed 's/\(.\)..$/.\1/'
I didn't see the predefined to start with as I was using the normal Tree List on the left instead of the UI Customizer version (mobile/responsive) that puts them at the top.   Didn't notice the scroll bar at the bottom so that is my fault.  Also as I am not that good with linux based alias/symlink, I just used the one I had to add to navbartemp to fix the SoC.

Anyways, looking forward to seeing more additions and improvements.  If you need me to test anything just let me know. :)

**Comment by LazeMSS** [comment]
Awesome thanks for getting back - forgot to test without UI customizer. That is fixed in next version.

**Comment by SureshotM6** [comment]
> As for the vcgencmd. This was the other predefined. cat /sys/class/thermal/thermal_zone0/temp | sed 's/\\(.\\)..$/.\1/'

Note this that command doesn't round up properly and also would have issues around 0^C (which really shouldn't be expected unless someone keeps their Pi in a freezer though).

I would suggest to use this command instead.  It's also less CPU time to run (although both are tiny):
`awk '{print $0/1000}' /sys/class/thermal/thermal_zone0/temp`

**Comment by ken536** [comment]
I would like an option to ask for temperatures using the terminal (I use klipper)

**Comment by LazeMSS** [comment]
> I would like an option to ask for temperatures using the terminal (I use klipper)

Im not sure how that works. I have no experience with kipper

**Comment by ken536** [comment]
I fact real simple: I send TEMP_CASE to the terminal and it responds with a value I can set in the option. This could be a single number:

> Send: TEMP_CASE
Recv: // Case:
Recv: // Temperature: 37.05 C
Recv: // Pressure: 1002.53 hPa
Recv: // Humidity: 11.93%

This way I could also use it to show the humidity

**Comment by LazeMSS** [comment]
@ken536  please post as seperate report :)

**Comment by LazeMSS** [comment]
Should be fixed in: https://github.com/LazeMSS/OctoPrint-TopTemp/releases/tag/0.0.0.3

I'm closing for now - if not fixed please reopen this :)
