### ISSUE TITLE
Read Info from the printer?

### ISSUE THREAD

**Issue by AftDawn** [LazeMSS/OctoPrint-TopTemp#50]
Is there any way to read info from the printer.
I'd like to show the x y and z in the graph through M114 but it can't send gcode to the printer, nor do I know of a way to send gcode from the command section.

**Comment by LazeMSS** [comment]
Do you want a graph/display of the different axis? I can maybe understand Z but I think you should look into alternative plugins for this like https://plugins.octoprint.org/plugins/DisplayLayerProgress/

**Comment by LazeMSS** [comment]
No response...
