### ISSUE TITLE
Feature request: Pi internal voltage?

### ISSUE THREAD

**Issue by bladeslapper** [LazeMSS/OctoPrint-TopTemp#51]
I presume that since it is not on your "system" list that it is not possible to query and then display the internal voltage of the Pi?

**Comment by LazeMSS** [comment]
You could just run a custom command like:
`vcgencmd measure_volts core| cut -d= -f 2 | cut -b1-6`

Basically anything you can ask the OS/Bash about the plugin can display
![image](https://user-images.githubusercontent.com/69049371/116003795-ddb80400-a5ff-11eb-9fb2-4347434297bb.png)

**Comment by bladeslapper** [comment]
thanks
