### ISSUE TITLE
With no icon, Top Temp text does not align with other text (class navbar-text) on navbar

### ISSUE THREAD

**Issue by ManuelMcLure** [LazeMSS/OctoPrint-TopTemp#52]
This is an example with Navbar Clock and Navbar Temp enabled, Discorded theme in UI Customizer:
![image](https://user-images.githubusercontent.com/9875787/130544357-96d9a5ed-cd98-4b07-9121-6737153e2f97.png)
If I select "Align icons to the left" it looks like:
![image](https://user-images.githubusercontent.com/9875787/130544479-9caf4911-1d57-4e8e-b85d-e339f5c79867.png)
Both Navbar Clock and Navbar Temp just set the class to "navbar-text"
With icons and "Align icons to the left":
![image](https://user-images.githubusercontent.com/9875787/130544949-9422bc23-3c22-4e65-b7cf-fbbe8c472b81.png)

**Comment by LazeMSS** [comment]
Thanks - will be fixed soon.

**Comment by LazeMSS** [comment]
Fixed in 0.0.1.5
