### ISSUE TITLE
[Feature Request]: Allow popovers to be sticky

### ISSUE THREAD

**Issue by jneilliii** [LazeMSS/OctoPrint-TopTemp#53]
It would be nice to be able to freeze the popover on the graphs to allow for freezing them in view for snipping screenshots.

**Comment by LazeMSS** [comment]
Will add a "screenshot option"

**Comment by LazeMSS** [comment]
$('#navbar_plugin_toptemp_tool0').popover('show') :)

**Comment by LazeMSS** [comment]
https://github.com/LazeMSS/OctoPrint-TopTemp/tree/develop

**Comment by LazeMSS** [comment]
Fixed in 0.0.1.5
