### ISSUE TITLE
[FR] Separator/Spacer

### ISSUE THREAD

**Issue by electronicm** [LazeMSS/OctoPrint-TopTemp#57]
It would increase clarity if you could place separators between icons.
Not so Importent: It would be even more ingenious if you could bind these separators to the status "Only show while printer is printing", "Hide when not operational", "Only show while icons left/right are displayed".

Example idle:
CPUTemp   CPULoad

Example heating bed:
Bed   |   CPUTemp   CPULoad

Example printing:
Layer   %Completed   |   Bed   Tool0   |   CPUTemp   CPULoad

**Comment by LazeMSS** [comment]
Working on it.

**Comment by LazeMSS** [comment]
Included in: https://github.com/LazeMSS/OctoPrint-TopTemp/releases/tag/0.0.1.6

**Comment by electronicm** [comment]
This works also like a charm.
Is there still a possibility that you add the option "Show separator on left" or a DropDown with "none, left, right, both"?

**Comment by LazeMSS** [comment]
Just to understand - why do you want the seperator on the left etc. I understand the grouping of items but why left, none etc.
