### ISSUE TITLE
How do you add a custom temp....specifically a Chamber sensor?  

### ISSUE THREAD

**Issue by irwinpks** [LazeMSS/OctoPrint-TopTemp#62]
How do you add a custom temp....specifically a Chamber sensor?  An M105 returns this

Send: M105
Recv: ok B:28.1 /0.0 CT:-82.4 /0.0 T0:28.2 /0.0

The CT is not correctly connected (yet), but I'd like to read that -82.4 into Top Temp.

please advise.

--------------------------------------
I have this in my klipper printer.cfg

#####################################################################
# 	Chamber Thermistor
#####################################################################
[thermistor NTC_10k_3940k_beta]
temperature1: 25
resistance1: 10000
beta: 3940

[temperature_sensor chamber]
sensor_type:NTC_10k_3940k_beta
sensor_pin: PF6
gcode_ID: CT

**Comment by LazeMSS** [comment]
Setup a custom temp:
Type:
`From printer`
Regexp:
`CT:([^ ]+)`

Try that

**Comment by Sonicboom247** [comment]
will this work the same for a board thermistor? i have added one to T1 and although in terminal I can see temps, nothing is populating in the toolbar
Recv:  T:20.62 /0.00 B:23.71 /0.00 M:25.99 /0.00 @:0 B@:0
[...]
Recv:  T:20.66 /0.00 B:23.67 /0.00 M:25.80 /0.00 @:0 B@:0
[...]
Recv:  T:20.74 /0.00 B:23.59 /0.00 M:25.91 /0.00 @:0 B@
![Screenshot 2021-12-03 113418](https://user-images.githubusercontent.com/84334417/144638658-35b31414-3190-4371-8b68-3a10c04e8ceb.jpg)
:0

**Comment by LazeMSS** [comment]
Which value do you want to be displayed?

**Comment by Sonicboom247** [comment]
It is set as T1 for board thermistor, it's just not showing in the toolbar

**Comment by LazeMSS** [comment]
Yearh i kinda flying blind here :)
Which one of these values: 
`Recv: T:20.66 /0.00 B:23.67 /0.00 M:25.80 /0.00 @:0 B@:0`
do you want to be displayed?
Is it the M:25.80 - then you need:
`M:([^ ]+)`

**Comment by Sonicboom247** [comment]
![Screenshot 2021-12-03 113418](https://user-images.githubusercontent.com/84334417/144714583-ce2592dc-6dc8-410f-8a19-519dd9459546.jpg)
Yes, that is exactly what i needed!, my apologies for not being more specific

**Comment by LazeMSS** [comment]
No problem
