### ISSUE TITLE
Graph line color setting accidentally named "Graph line width"

### ISSUE THREAD

**Issue by SureshotM6** [LazeMSS/OctoPrint-TopTemp#7]
Just a simple typo in the settings jinja file.  There are currently 2 settings named "Graph line width", but the second controls the color not the width:

https://github.com/LazeMSS/OctoPrint-TopTemp/blob/main/octoprint_toptemp/templates/toptemp_settings.jinja2#L173

**Comment by LazeMSS** [comment]
Should be fixed in https://github.com/LazeMSS/OctoPrint-TopTemp/releases/tag/0.0.0.2

Please reopen if not fixed/working.
