### ISSUE TITLE
Help with regexp for a special temp sensor needed

### ISSUE THREAD

**Issue by Caipitrooper** [LazeMSS/OctoPrint-TopTemp#70]
Hi,
like issue #18 I too have the problem of getting the temperature back from a temperature sensor that is
replied from a M105. My temperature sensor is named "M:". I set it up this way in Klipper and this is the temp sensor
of the STM32 on the Spider board.

The M105 looks like this:

![image](https://user-images.githubusercontent.com/76991146/161443816-4668bd2e-84a8-4c24-b90a-1ea81d8fbafd.png)

I set the custom temp sensor and regexp to this:

![image](https://user-images.githubusercontent.com/76991146/161443864-55001c69-157c-41ce-b9cd-71204f8b3e24.png)

Regarding to the Regex Tester (https://de.infobyip.com/regularexpressioncalculator.php) it should give back the right value:

![image](https://user-images.githubusercontent.com/76991146/161443934-b40ca77f-db4d-4b2b-926a-e052c3674dc8.png)

However, I just get a waiting circle:

![image](https://user-images.githubusercontent.com/76991146/161444052-466e786a-699c-460b-9c53-65ea4d9dcb5e.png)

What would be the correct expression to get the temperature displayed?
Thanks a lot in advance.

**Comment by LazeMSS** [comment]
Maybe just try:
M:([^ ]+)

https://regex101.com/ is a very good regexp editor

**Comment by Caipitrooper** [comment]
It worked with this regexp, thank you very much. Issue can be closed.
