### ISSUE TITLE
[Feature Request] Add ability to display both Celsius and Fahrenheit

### ISSUE THREAD

**Issue by puterboy** [LazeMSS/OctoPrint-TopTemp#74]
Love this plugin!
Add ability to display both Celsius and Fahrenheit where the secondary scale is displayed in parentheses (like in the Navbar Temperature plugin).
This is important in the U.S. where we still "think" Fahrenheit but specify tool and bed temps in Celsius.

**Comment by LazeMSS** [comment]
Should be fixed in https://github.com/LazeMSS/OctoPrint-TopTemp/releases/tag/0.0.2.0 - please reopen if not working/fixed as expected

**Comment by puterboy** [comment]
Thanks! Seems to be working well!
