### ISSUE TITLE
[Feature Request] Ability to trigger action if temperature too low/too high

### ISSUE THREAD

**Issue by puterboy** [LazeMSS/OctoPrint-TopTemp#78]
Action could be either a user-specified system command or Gcode to send to printer if temperature is too high or too low based on the colorization cutoffs (or maybe a separate user-specified number).

I know this is not directly related to displaying the temps but since your *excellent* plugin collects all this data in one place, it would be an easy and natural place to trigger an action...

**Comment by LazeMSS** [comment]
Out of scope - I think there are other plugins that will handle this.

**Comment by puterboy** [comment]
I understand that it could be out of scope but it seems a shame to have repeat the data collection with another plugin. So still would be nice :)
