### ISSUE TITLE
[BUG] Can't change sort order since conflicts with Upload locally/Upload to SD card

### ISSUE THREAD

**Issue by puterboy** [LazeMSS/OctoPrint-TopTemp#79]
When I try to change the sort order on the "General" tab by using my mouse to move the items, the screen darkens and gives me the option on the left to "Upload locally" and on the right to "Upload to SD card".

To change the sort order, I had to manually move lines in config.yaml as a workaround.

**Comment by LazeMSS** [comment]
Hmm... im running UI Customizer - it handles this bug so maybe try installing that?

**Comment by puterboy** [comment]
I have been  using Themeify...
But as I said, I solved it for myself by manually editing config.yaml but others might not be comfortable with that :)

**Comment by LazeMSS** [comment]
You should really use UI customizer. Much better 🤪

I will implement the drag and drop fix ASAP

**Comment by puterboy** [comment]
Thanks.
I'm sure it's much better :) just haven't had the time yet to play with it :)

**Comment by LazeMSS** [comment]
Should be fixed in https://github.com/LazeMSS/OctoPrint-TopTemp/releases/tag/0.0.2.0 - please reopen if not working/fixed as expected

**Comment by puterboy** [comment]
Thanks! Works great!

**Comment by puterboy** [comment]
Thanks! Works great now!
