### ISSUE TITLE
[FEATURE REQUEST] Add parameter to specify displayed history length of graphs

### ISSUE THREAD

**Issue by puterboy** [LazeMSS/OctoPrint-TopTemp#82]
Would be great to be able to set the maximum period length graphed by each parameter. This period would represent how much history is then saved and displayed for each parameter, perhaps with one general number that is optionally overridable for each individual parameter.

This period would be reflected both in the drop-down as well as in the trace in the navbar itself.

**Comment by LazeMSS** [comment]
Should be fixed in https://github.com/LazeMSS/OctoPrint-TopTemp/releases/tag/0.0.2.0 - please reopen if not working/fixed as expected

**Comment by puterboy** [comment]
Thanks!!!

**Comment by puterboy** [comment]
Thanks! Works great!
