### ISSUE TITLE
[BUG?] Temperature time scale oscillates between 10min and 10-sampling period

### ISSUE THREAD

**Issue by puterboy** [LazeMSS/OctoPrint-TopTemp#83]
The length of the temperature axis varies from 10min [-10 to 0] right before a new sample is captured to (10min-sampling period) [-(10-sampling period) to 0] right after a new sample is capture.
For example, I sample one of my sensors with a custom command with an interval of 300 seconds. That means that every 5 minutes, the x-axis starts at -5minutes, then increases monotonically to -10minutes then suddenly drops back to -5min.

This is confusing to read since the scale length is constantly growing & shrinking -- and even worse you get non-integer numbers like -8.9
A cleaner implementation would be to fix the start of the scale at -10min (and hence the length of the scale) and then have data fall off the end naturally

(even better would be to fix this and implement my feature request https://github.com/LazeMSS/OctoPrint-TopTemp/issues/82 so that the length of the scale would be configurable)

**Comment by LazeMSS** [comment]
Should be fixed in https://github.com/LazeMSS/OctoPrint-TopTemp/releases/tag/0.0.2.0 - please reopen if not working/fixed as expected
