### ISSUE TITLE
[Bug] Misspelling of word "seperator" -- should be "separator"

### ISSUE THREAD

**Issue by puterboy** [LazeMSS/OctoPrint-TopTemp#86]
Appears in options under "Decimal seperator" and "Show seperator to right"

**Comment by LazeMSS** [comment]
You don't like the Danish spelling ;)

**Comment by LazeMSS** [comment]
https://github.com/LazeMSS/OctoPrint-TopTemp/blob/92cf5ac819c476cc8aaf7f702416cae947c750ba/octoprint_toptemp/templates/toptemp_settings.jinja2#L182

**Comment by puterboy** [comment]
I was just being pedantic I suppose... :)

**Comment by LazeMSS** [comment]
Should be fixed now: https://github.com/LazeMSS/OctoPrint-TopTemp/releases/tag/0.0.2.1

**Comment by puterboy** [comment]
Thanks!!!
