### ISSUE TITLE
Custom Temp Not Updated

### ISSUE THREAD

**Issue by ryancasler** [LazeMSS/OctoPrint-TopTemp#92]
I have a custom temp that updates by reading a txt file on my Pi.  I put the command into the plugin and the test works correctly and reads the correct temp.   But the temp displayed on the menu bar is incorrect.
![image](https://user-images.githubusercontent.com/30270489/210121233-7e110e9c-5774-4bf9-93bb-cae405a4a375.png)
![image](https://user-images.githubusercontent.com/30270489/210121246-c68b5013-3cb0-4fa4-8acb-908e541c143d.png)
![image](https://user-images.githubusercontent.com/30270489/210121266-eb94bf5a-9def-4fae-9be0-9ccaaa695f1e.png)

**Comment by LazeMSS** [comment]
Strange - my first thought was maybe some fahrenheit conversion but that does not match the numbers you posted.
Tried on my own setup and it works fine.

**Comment by ryancasler** [comment]
And it does subsequently on my system as well.  Must have been a random failure.  I will continue to monitor and re-open the issue if it pops up again.
