### ISSUE TITLE
BUG: Histogram length doesn't work for faster sampling rates

### ISSUE THREAD

**Issue by puterboy** [LazeMSS/OctoPrint-TopTemp#94]
I set the "Show data this many seconds old on graph" to 3600 seconds (60 minutes) for all my sensors.
For the sensors that update every 5 seconds, only about 26 minutes of data is displayed.
For the sensors that update every 30 seconds, the full 60 minutes of data is shown.

I suspect that not enough buffer is reserved to hold the number of samples required to sample 5x/sec times 60 minutes.
Presumably enough buffer data should be allocated or alternatively, the UI should give a warning if the sampling rate times the histogram length is too large.

**Comment by LazeMSS** [comment]
Fixed in the next release - please consider pick up coding and help fixing these bug by making pull request :)

**Comment by puterboy** [comment]
Sure. I actually looked through the code but couldn't find the issue.

**Comment by puterboy** [comment]
Any idea on when this may be released? Thanks

**Comment by LazeMSS** [comment]
Yes hopefully tonight.

**Comment by LazeMSS** [comment]
Fixed in: https://github.com/LazeMSS/OctoPrint-TopTemp/releases/tag/0.0.2.3
